CC = gcc
LD = gcc
CFLAGS = -O3 -ftree-vectorize -march=native -ffast-math
LDFLAGS = -lpthread -lm
RM = /bin/rm -f
PROG = galsim

$(PROG):
	$(LD) $(CFLAGS) $(LDFLAGS) -o $(PROG) galsim.c


clean:
	$(RM) $(PROG)
